### ISSUE TITLE
dark mode checking ?

### ISSUE THREAD

**Issue by jemadux** [Rowan441/Rowan441.github.io#1]
personally in my  pc i am using dark reader with default settings .. 
as you can see here https://i.postimg.cc/gkG53j7Y/2023-02-01-19-57-44.png
so must be something that we can avoid showing the moves .

**Comment by Rowan441** [comment]
I don't have a dark reader to test, but I believe it should be fixed
[Rowan441.github.io](https://rowan441.github.io/)
